// game
export const INIT_GAME          = 'INIT_GAME'
export const START_GAME         = 'START_GAME'
export const MARK_TILE          = 'MARK_TILE'
export const REMOVE_LAYER       = 'REMOVE_LAYER'
export const RENDER_LAYER       = 'RENDER_LAYER'
export const SET_BOARD          = 'SET_BOARD'
export const SET_BOARDS         = 'SET_BOARDS'
export const SET_LAYOUTS        = 'SET_LAYOUTS'
export const SHUFFLE            = 'SHUFFLE'
export const SHUFFLE_AT_ONCE    = 'SHUFFLE_AT_ONCE'
export const START_OVER         = 'START_OVER'
export const START_OVER_AT_ONCE = 'START_OVER_AT_ONCE'
export const TOGGLE_ANIMATION   = 'TOGGLE_ANIMATION'
export const TIME_TRAVEL        = 'TIME_TRAVEL'

// editor
export const TOGGLE_SLOT     = 'TOGGLE_SLOT'
export const INIT_EDITOR     = 'INIT_EDITOR'
export const ADD_TILE        = 'ADD_TILE'
export const REMOVE_TILE     = 'REMOVE_TILE'
export const RESET_EDITOR    = 'RESET_EDITOR'
export const SAVE_LAYOUT     = 'SAVE_LAYOUT'
export const SAVED_LAYOUT    = 'SAVED_LAYOUT'
export const SET_LAYOUT      = 'SET_LAYOUT'
export const TOGGLE_MODE     = 'TOGGLE_MODE'
